//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spendings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Эко_РегионыEntities : DbContext
    {
        public Эко_РегионыEntities()
            : base("name=Эко_РегионыEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<regions_> regions_ { get; set; }
        public virtual DbSet<spendings_> spendings_ { get; set; }
        public virtual DbSet<states_> states_ { get; set; }
    }
}
