//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spendings
{
    using System;
    using System.Collections.Generic;
    
    public partial class spendings_
    {
        public int Код { get; set; }
        public Nullable<int> Код_региона { get; set; }
        public Nullable<int> Код_статьи_затрат { get; set; }
        public Nullable<double> Сумма { get; set; }
        public string Год { get; set; }
    
        public virtual regions_ regions_ { get; set; }
        public virtual states_ states_ { get; set; }
    }
}
